### ISSUE TITLE
sensor/error.h not found.

### ISSUE THREAD

**Issue by sophiekovalevsky** [bastienleonard/pysensors#1]
I tried to install this package into my machine and there is no folder name within the repo called sensor.

There is a library call in sensorsmodule.c file that is causing this message at shell: sensorsmodule.c:32:27: fatal error: sensors/error.h: file not found.

Thanks for this awesome binding.

**Comment by bastienleonard** [comment]
This isn't mentioned in the documentation (sorry about that), but sensors/error.h is part of lm_sensors and must be installed separately.

On Archlinux, I just had to install the lm_sensors package. On Ubuntu or Debian, it seems like you'd need to install the libsensors4-dev package.

**Comment by sophiekovalevsky** [comment]
I got it.
The issue is that I've previously installed lm_sensors on my fedora system and it didn't work.

---

For fedora developers, install lm_sensors-devel package.
