### ISSUE TITLE
install with pip fails

### ISSUE THREAD

**Issue by TurBoss** [bastienleonard/pysensors#3]
Hi

I'm trying to install pysensors from pip and it fails with 

```
Collecting pysensors
  Downloading PySensors-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-b7_uqqru/pysensors/setup.py", line 4, in <module>
        import sensors
      File "/tmp/pip-build-b7_uqqru/pysensors/sensors/__init__.py", line 21, in <module>
        MAJOR_VERSION = int(VERSION.split('.', 1)[0])
    TypeError: a bytes-like object is required, not 'str'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b7_uqqru/pysensors/
```

the same with pip3
I  have libsensors4-dev installed

Thanks

**Comment by bastienleonard** [comment]
Hi,

It seems like you're installing a different package: https://pypi.python.org/pypi/PySensors/0.0.3
Looking at the error, I guess you're using Python 3+ and this package doesn't support it.
If you want to install my module, please build it yourself: http://pysensors.readthedocs.io/en/latest/building.html#building-the-module

**Comment by TurBoss** [comment]
ok i'm sorry

thanks
